dependencies:
- name: nginx-ingress
  version: ~0.22.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: cert-manager
  version: ~0.5.0
  repository: https://kubernetes-charts.storage.googleapis.com/