apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ required "web.domain value required" .Values.web.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80