version: '2.1'
services:
  kubectldata:
    image: cirros
    container_name: kubectldata
  kubectl:
    build: .
    container_name: kubectl
    hostname: kubectl
    volumes:
      - checkerskubebashhistory:/root/bash
      - checkerskubeconfig:/root/.kube
      - checkerskubehelmconfig:/root/.helm
      - checkerskubegcloudconfig:/root/.config/gcloud
    volumes_from:
      - kubectldata
    ports:
      - "8001:8001"
    environment:
      HISTFILE: "/root/bash/.bash_history"
volumes:
  checkerskubebashhistory:
    name: checkerskubebashhistory
  checkerskubeconfig:
    name: checkerskubeconfig
  checkerskubegcloudconfig:
    name: checkerskubegcloudconfig
  checkerskubehelmconfig:
    name: checkerskubehelmconfig