apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    email: jan@monger.com
    server: https://acme-v02.api.letsencrypt.org/directory #staging/test: https://acme-staging-v02.api.letsencrypt.org/directory
    http01: {}
    privateKeySecretRef:
      name: letsencrypt-staging